version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install dependencies"
  build:
    commands:
      - echo "Build frontend"
  post_build:
    commands:
      - echo "Deploy frontend"

